### PR TITLE
Introduce support for pipelined requests, key prefix stripping, custom IPs, and Unix sockets

### PR DESCRIPTION
**Pull request by adesjardins-stripe**
Based on the work by Fei here: https://github.com/memcached/mctester/pull/3/files. There are a couple of additional minor changes, and the new modifications to `protocol` were propagated to `server` as well.

### CODE REVIEW

**Comment by adesjardins-stripe** [comment]
My 2nd PR is directed at this branch in my fork for now: https://github.com/adesjardins-stripe/mctester/pull/2

When this PR is merged, I'll redirect that one to here (and also add module support for the new command).

**Comment by adesjardins-stripe** [comment]
@dormando (sorry to ping, just want to make sure it doesn't fly under your radar)

**Comment by dormando** [comment]
Sorry, I haven't been in front of a computer much lately. I'll review it soon.

**Comment by dormando** [comment]
sometimes life hits you hard, sometimes it hits you harder, I guess...

Looked through this more carefully just now and no complaints. it's been merged; go ahead and open the next PR when you get a chance. Hopefully I'll respond in a day instead of a month.

**Comment by adesjardins-stripe** [comment]
Hey, that's alright! Life is infinitely more important than a couple PRs. I opened the other one, but you can just get to it when you get to it. Thanks!

**Pull request merged**
